# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: sauce-labs-variables
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
  
#Excellent docs on .NET Core steps: 
#https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#feedback
steps:
- script: set
  displayName: Show all variables

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
 #need to use the vso tasks so that the env variables persist trhough tasks in ADO
 - powershell: ./ setEnvironmentVariables.ps1 
   arguments: '$env:SAUCE_USERNAME $env:SAUCE_ACCESSKEY'

- task: VSTest@2
  displayName: 'Selenium Tests'
  inputs:
    testAssemblyVer2: '**\$(BuildConfiguration)\**\*.Tests.dll'
    uiTests: true
